import type { GlossaryTerm } from '@/features/core/components/InfoModal.component';

export const GLOSSARY_BASE: GlossaryTerm[] = [
  { term: 'Ahorro', definition: 'Dinero que guardas en lugar de gastar. Tu ahorro mensual es $2,000 — lo primero que separas cuando cobras.' },
  { term: 'Ahorro mensual objetivo', definition: 'La cantidad que decides ahorrar cada mes para llegar a tu meta. En tu caso: $2,000.' },
  { term: 'Calidad de vida', definition: 'Tipo de gasto que mejora tu comodidad o bienestar, pero no es urgente. Ejemplo: una almohada mejor.' },
  { term: 'Capricho', definition: 'Gasto impulsivo sin justificación racional. No aporta valor real, solo satisfacción momentánea.' },
  { term: 'Categoría de gasto', definition: 'Grupo al que pertenece cada gasto. Tus categorías: Alimentación, Higiene, Salud, Casa, Gym, Claude, Ocio, Imprevistos, Caprichos, Tecnología.' },
  { term: 'Comodidad', definition: 'Qué tanto mejora algo tu vida cotidiana en términos de facilidad y confort.' },
  { term: 'Compra impulsiva', definition: 'Compra no planeada motivada por emoción, no por necesidad o razonamiento.' },
  { term: 'Costo de oportunidad', definition: 'Lo que renuncias cuando gastas dinero. Si gastas $100 en algo innecesario, renuncias a $100 de ahorro.' },
  { term: 'Decisor de compras', definition: 'Herramienta que evalúa si una compra vale la pena basándose en precio, impacto y tiempo de espera.' },
  { term: 'Depreciación hedónica', definition: 'La emoción que sientes al comprar algo nuevo dura poco. Después de días o semanas, la satisfacción cae drásticamente.' },
  { term: 'Disponible', definition: 'Lo que te queda para gastar libremente después de separar el ahorro y cubrir todos los gastos del mes.' },
  { term: 'Excedido', definition: 'Cuando gastas más de lo que tenías presupuestado en una categoría.' },
  { term: 'Flujo de caja', definition: 'El movimiento de dinero que entra (ingresos) y sale (gastos) en un período. Positivo = ganas más de lo que gastas.' },
  { term: 'Gasto fijo', definition: 'Gasto que se repite igual cada mes. Ejemplo: renta, suscripción, gym.' },
  { term: 'Gasto variable', definition: 'Gasto que cambia de monto mes a mes. Ejemplo: comida, transporte, entretenimiento.' },
  { term: 'Ingreso extra', definition: 'Dinero que entra esporádicamente: bonos, freelance, ventas, regalos.' },
  { term: 'Ingreso fijo', definition: 'Salario o pago que recibes igual cada mes o período. Predecible y confiable.' },
  { term: 'Ingreso variable', definition: 'Ingreso que cambia según el trabajo realizado o ventas. Ejemplo: comisiones.' },
  { term: 'Liquidez', definition: 'Dinero disponible de inmediato (efectivo o en cuenta). Alta liquidez = puedes pagar lo que necesitas sin esperar.' },
  { term: 'Meta financiera', definition: 'Un objetivo monetario concreto con monto y plazo. Tu meta: $15,000 de ahorro.' },
  { term: 'Necesidad', definition: 'Gasto que no puedes evitar sin afectar tu salud, seguridad o funcionamiento básico.' },
  { term: 'Patrimonio neto', definition: 'Total de lo que has ahorrado o acumulado hasta ahora. Es tu riqueza real en este momento.' },
  { term: 'Presupuesto', definition: 'Plan que asigna cuánto puedes gastar en cada categoría antes de que empiece el mes.' },
  { term: 'Prioridad', definition: 'En la wishlist: Alta = lo necesitas pronto, Media = puedes esperar, Baja = es un deseo.' },
  { term: 'Productividad', definition: 'Qué tanto te ayuda algo a hacer más o mejor trabajo. Alta productividad = justifica el gasto.' },
  { term: 'Proyección', definition: 'Cálculo de cuánto tendrás ahorrado en meses futuros, asumiendo que sigues ahorrando $2,000/mes.' },
  { term: 'Puntaje', definition: 'Número de 0 a 10 que mide si una compra vale la pena. Se calcula con precio, impacto y días de espera.' },
  { term: 'Regla de las 72 horas', definition: 'Antes de comprar algo entre $20 y $100, espera 3 días. Si sigues queriéndolo, la compra es más racional.' },
  { term: 'Regla de los 7 días', definition: 'Para compras mayores de $100, espera una semana completa antes de decidir.' },
  { term: 'Salud financiera', definition: 'Estado general de tus finanzas: ahorras, no debes, tienes plan. Como la salud física, se cuida con hábitos.' },
  { term: 'Semáforo financiero', definition: 'Sistema de colores (verde/amarillo/rojo) que indica si una compra es prudente ahora mismo.' },
  { term: 'Valor percibido', definition: 'Lo que crees que vale algo para ti. A veces es mayor que el precio real; otras veces menor.' },
  { term: 'Wishlist inteligente', definition: 'Lista de cosas que quieres comprar, filtrada por un sistema que te hace esperar antes de decidir.' },
  { term: 'Zero-based budgeting', definition: 'Técnica donde cada peso de tus ingresos tiene un destino asignado. Nada queda "sin plan". Suma 0 al final.' },
];
